[package]
name = "lightdash-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlElement",
    "Window",
    "CanvasRenderingContext2d",
    "HtmlCanvasElement",
    "Chart",
    "ChartConfiguration",
    "ChartData",
    "ChartOptions",
    "ChartType",
    "ChartDataset",
    "ChartPlugins",
    "ChartScales",
    "ChartTitle",
    "ChartLegend",
    "ChartTooltip",
    "ChartAnimation",
    "ChartLayout",
    "ChartInteraction",
    "ChartResponsive",
    "ChartMaintainAspectRatio",
    "ChartElements",
    "ChartElementsOptions",
    "ChartElementsLine",
    "ChartElementsPoint",
    "ChartElementsBar",
    "ChartElementsArc",
    "ChartElementsRectangle",
    "ChartElementsText",
    "ChartElementsImage",
    "ChartElementsLineOptions",
    "ChartElementsPointOptions",
    "ChartElementsBarOptions",
    "ChartElementsArcOptions",
    "ChartElementsRectangleOptions",
    "ChartElementsTextOptions",
    "ChartElementsImageOptions",
    "ChartScalesOptions",
    "ChartScalesLinearOptions",
    "ChartScalesLogarithmicOptions",
    "ChartScalesCategoryOptions",
    "ChartScalesTimeOptions",
    "ChartScalesRadialOptions"
]}
gloo = "0.8"
gloo-net = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }