[package]
name = "lightdash-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen-futures = "0.4"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
thousands = "0.2"
plotters = "0.3"
plotters-canvas = "0.3"
gloo-timers = "0.2"
reqwest = { version = "0.11", features = ["json"] }
dotenv = "0.15"

[lib]
crate-type = ["cdylib", "rlib"]
