[package]
name = "lightdash-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlElement", "HtmlInputElement", "HtmlCanvasElement"] }
gloo-net = "0.2"
gloo-timers = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
wasm-logger = "0.2"
console_error_panic_hook = "0.1"
js-sys = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]
