[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "styles", "static"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false

[clean]
dist = "dist"

[tools]
wasm-bindgen = "0.2.89"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "./styles/main.css", "-o", "./dist/main.css"] 