global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
    channel: '#lightdash-alerts'
    send_resolved: true
    title: '{{ .GroupLabels.alertname }}'
    text: |-
      {{ range .Alerts }}
      *Alerte:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Sévérité:* {{ .Labels.severity }}
      *Début:* {{ .StartsAt }}
      {{ end }} 