version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/frontend/target
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_SPARKSEER_API_KEY=${NEXT_PUBLIC_SPARKSEER_API_KEY}
      - NEXT_PUBLIC_NODE_PUBKEY=${NEXT_PUBLIC_NODE_PUBKEY}
    command: sh -c "cd frontend && trunk serve --address 0.0.0.0 --port 3000"

volumes:
  cargo-cache:
  target-cache: 