version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    environment:
      - RUST_LOG=debug
      - SPARKSEER_API_KEY=${SPARKSEER_API_KEY}
      - NODE_PUBKEY=${NODE_PUBKEY}
      - API_URL=${API_URL}
      - ML_URL=${ML_URL}
    restart: unless-stopped

volumes:
  cargo-cache:
  target-cache: 