[build]
  command = "./install.sh && ./build.sh"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  RUST_VERSION = "1.70"

[[plugins]]
  package = "@netlify/plugin-rust"
  [plugins.inputs]
    buildCommand = "cd frontend && trunk build --release"
    publishDirectory = "frontend/dist" 